server:
  rootPath: '/apis/*'
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
    - type: console
      timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
    com.codahale.metrics.collectd: ERROR
    io.appform.idman: ${LOG_LEVEL}
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

db:
  driverClass: org.mariadb.jdbc.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_CONNECTION_STRING}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.use_sql_comments: true
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 8
  initialSize: 8
  logAbandonedConnections: true
  logValidationErrors: true
  checkConnectionWhileIdle: true
  checkConnectionOnConnect: true
  validationQueryTimeout: 1s
  removeAbandoned: true
  evictionInterval: 30s
  minIdleTime: 1m

authenticationCore:
  enabled: ${AUTH_ENABLED}
  domain: ${DOMAIN}
  server: ${SERVER_ENDPOINT}
  secureEndpoint: ${SECURE_ENDPOINT}
  sessionDuration: 15d

  jwt:
    issuerId: idman
    privateKey: ${JWT_PRIVATE_KEY}
    serviceName: projectstepone

  provider:
    type: GOOGLE_AUTH
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    loginDomain: ${GOOGLE_DOMAIN}

idmanAuthConfig:
  enabled: ${AUTH_ENABLED}
  serviceName: idman
  authEndpoint: ${SERVER_ENDPOINT}
