server:
  rootPath: '/apis/*'
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
    com.codahale.metrics.collectd: ERROR
    io.appform.idman: DEBUG
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

db:
  driverClass: org.mariadb.jdbc.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_CONNECTION_STRING}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 8
  initialSize: 8
  logAbandonedConnections: true
  logValidationErrors: true
  checkConnectionWhileIdle: true
  checkConnectionOnConnect: true
  validationQueryTimeout: 1s
  removeAbandoned: true
  evictionInterval: 30s
  minIdleTime: 1m

authenticationCore:
  server: ${SERVER_URL}
  sessionDuration: 15d

  jwt:
    issuerId: ${JWT_ISSUER_ID}
    privateKey: ${JWT_PRIVATE_KEY}
