server:
  rootPath: '/apis/*'
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
    com.codahale.metrics.collectd: ERROR
    io.appform.idman: DEBUG
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

db:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password: password
  url: jdbc:mariadb://localhost/idman_db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
#    hibernate.show_sql: true
#    hibernate.format_sql: true
#    hibernate.use_sql_comments: true
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 8
  initialSize: 8
  logAbandonedConnections: true
  logValidationErrors: true
  checkConnectionWhileIdle: true
  checkConnectionOnConnect: true
  validationQueryTimeout: 1s
  removeAbandoned: true
  evictionInterval: 30s
  minIdleTime: 1m

authenticationCore:
  domain: idman.test
  server: idman.test:8080
  secureEndpoint: false
  sessionDuration: 15d

  jwt:
    issuerId: projectstepone
    privateKey: ${JWT_PRIVATE_KEY}

idmanAuthConfig:
  serviceId: IDMAN
  authEndpoint: http://idman.test:8080
  allowedPaths:
    - /auth/login
    - /js
    - /css
    - /apis/idman
    - /apis/auth
    - ui/auth/login
  resourcePrefix: "/apis"