version: '3.3'
services:
   mariadb:
    image: mariadb:10.5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: idman_db
      MYSQL_USER: suser@%
      MYSQL_PASSWORD: password
   idman:
    container_name: idman
    build: .
    restart: always
    ports:
    - "8080:8080"
    - "8081:8081"
    volumes:
    - /var/log/idman
    environment:
      LOG_LEVEL: DEBUG
      DB_CONNECTION_STRING: jdbc:mariadb://mariadb/idman_db?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      SERVER_URL: http://localhost:8080
      JWT_ISSUER_ID: idmanlocal
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      PRESLEEP: 10
    depends_on:
      - mariadb
